### DISCUSSION TITLE
When I run larastan in level 6 or above

### DISCUSSION THREAD

**Discussion by waelsjaber** [larastan/larastan#1256] [Q&A] [answered]
When I run larastan in level  6 or above, I got an error as below:

![image](https://user-images.githubusercontent.com/58438216/171025140-fc00b80f-c6d9-419b-8716-9ae80d925118.png)

the file `phpstan.neon`  contains :

```
includes:
    - ./vendor/nunomaduro/larastan/extension.neon

parameters:

    paths:
        - app

    # The level 9 is the highest level
    level: 6
    ignoreErrors:
        - '#PHPDoc tag @var#'
```
How is the best way to solve this error ?
