### DISCUSSION TITLE
Problem with using larastan in gitlab ci

### DISCUSSION THREAD

**Discussion by marineusde** [larastan/larastan#1499] [Q&A] [answered]
I try to use larastan in my gitlab ci. With just phpstan it works perfectly.

My admins tried to use the current version of composer, but it doesnt help.

The error in the gitlab console is:
```
PHP Fatal error:  Uncaught Error: Interface "PHPStan\Collectors\Collector" not found in /home/gitlab-runner/builds/C9dbFuKp/0/dev/hubgrade/vendor/nunomaduro/larastan/src/Collectors/UsedViewFunctionCollector.php:13
```

.gitlab-ci.yml:
```
stages:
  - phpstan

cache:
  key: $CI_COMMIT_REF_SLUG
  paths:
    - .tmp/
    - vendor/

phpstan:
  stage: phpstan
  image: amd64/php:8.1-zts-buster
  script:  phpstan analyse -c phpstan.neon
  allow_failure: false
  before_script:
    - composer install --no-scripts --no-interaction --no-suggest --ansi
    - composer update
```

phpstan.neon:
```
includes:
    - ./vendor/nunomaduro/larastan/extension.neon

parameters:
    paths:
        - app
        - config
        - database/seeders
        - routes
        - resources/views
        - tests
    tmpDir: var/cache/ecs
    level: 6
    inferPrivatePropertyTypeFromConstructor: true
    checkMissingIterableValueType: false
    checkGenericClassInNonGenericObjectType: false
    scanFiles:
        - _ide_helper_models.php
```

**Comment by canvural** [comment, marked as answer]
Seems like somehow your PHPStan version is old. Please check the version of it. It should be 1.9.4 or higher

**Reply by marineusde** [reply]
Thanks for the idea. I checked the versions in the container after composer install:

phpstan: 1.9.5
larastan: 2.3.4

**Reply by szepeviktor** [reply]
Maybe you have PHPStan installed globally **and** in your dependencies...

**Reply by marineusde** [reply]
I removed the line with phpstan/phpstan from the composer.json and recreate the .lock-file now, but got the same error.

**Reply by szepeviktor** [reply]
What output do you get if you replace script with `which -a phpstan`?

**Reply by marineusde** [reply]
You are right :) With the which-command I found a global version on our gitlabserver installed with an old version... 

The solution in the the .gitlab-ci.yml is:

```
phpstan:
  stage: phpstan
  image: amd64/php:8.1-zts-buster
  script: php vendor/bin/phpstan analyse -c phpstan.neon
  allow_failure: false
  before_script:
    - composer install
```

Now it works with the "composer version" of phpstan in the project (now I have to update all gitlab-configs of the company, yeah)

**Reply by szepeviktor** [reply]
Use Composer scripts.

**Reply by marineusde** [reply]
Done, thank you for the great help :)

Now the solution in the .-gitlab-ci.yml is:
```
stages:
  - phpstan

cache:
  key: $CI_COMMIT_REF_SLUG
  paths:
    - .tmp/
    - vendor/

phpstan:
  stage: phpstan
  image: amd64/php:8.1-zts-buster
  script: composer phpstan
  allow_failure: false
  before_script:
    - composer install
```

Script in composer.json:
```
"phpstan": [
  "./vendor/bin/phpstan analyse"
],
```

How I can mark the solution in this discussion?
