### DISCUSSION TITLE
Check attributes model with ide-helper dont work

### DISCUSSION THREAD

**Discussion by marineusde** [larastan/larastan#1524] [Q&A] [answered]
I am using larastan and the package barryvdh/laravel-ide-helper. I dropped an attribute of a model and running the ide-helper-command. Now I try to run phpstan, but no errors was found. If I remove the extension of larastan in the phpstan.neon, the error was found:

Code-Example:
```
$modelVariable->foo_id = 1234;
```

```
Access to an undefined property App\Models\FooModel::$foo_id

```

I tried to delete the phpstan-cache, with no result. Do I have to configure the testing of models in larastan?

My phpstan.neon:
```
includes:
    - ./vendor/nunomaduro/larastan/extension.neon

parameters:
    paths:
        - app
        - config
        - database/seeders
        - routes
        - resources/views
        - tests
    tmpDir: var/cache/ecs
    level: 6
    inferPrivatePropertyTypeFromConstructor: true
    checkMissingIterableValueType: false
    checkGenericClassInNonGenericObjectType: false
    scanFiles:
        - _ide_helper_models.php
```

Versions:
- Laravel: 9.47.0
- PhpStan: 1.9.11
- Larastan: 2.4.0
