### DISCUSSION TITLE
Migrations not scanned in a module

### DISCUSSION THREAD

**Discussion by amenk** [larastan/larastan#1528] [Q&A] [answered]
We have a module and call

    # vendor/us/our-module/src/OurModuleServiceProvider.php:24
    public function boot()
    {
    ...
        $this->loadMigrationsFrom(__DIR__.'/Database/migrations');
    ...
    }

In the module's service provider.

We also have a user model in this module, which causes errors (level 3):

```
 ------ -------------------------------------------------------------------------- 
  Line   app/Notifications/Order.php                                               
 ------ -------------------------------------------------------------------------- 
  59     Access to an undefined property Us\OurModule\Models\User::$first_name.     
  61     Access to an undefined property Us\OurModule\Models\User::$city.           
  61     Access to an undefined property Us\OurModule\Models\User::$street.         
  61     Access to an undefined property Us\OurModule\Models\User::$street_number.  
  61     Access to an undefined property Us\OurModule\Models\User::$zip.            
  62     Access to an undefined property Us\OurModule\Models\Order::$benefit.   
```

My first guess would be, that larastan does not know where to find the right migrations for this model, because they are in the vendor folder.

Is an option or docblock or something to add those migrations to the scanner or do we have to manually ignore those errors?

**Comment by canvural** [comment, marked as answer]
Yes, you can specify custom migration folders: https://github.com/nunomaduro/larastan/blob/master/docs/custom-config-parameters.md#databasemigrationspath

**Reply by amenk** [reply]
Okay, looks like exactly what I am looking for. Unfortunately it does not work for my case, yet.
When I call `analyse --debug`, should those vendor-migrations be listed? Because they are not ...

I am using this path config:

```
    paths:
        - app/
        - database/
        - resources/
        - routes/
        - vendor/us/our-module/
    excludePaths:
        - tests/
        - vendor/
    databaseMigrationsPath:
        - vendor/us/our-module/src/Database/migrations
```
