### DISCUSSION TITLE
Getting different results running PHPStan locally vs in Github workflow

### DISCUSSION THREAD

**Discussion by geoff-maddock** [larastan/larastan#1584] [Q&A]
I started noticing this issue after doing some updates, including updating Larastan to ^2.0 (nunomaduro/larastan                   2.2.9 )

I have a CI step in my github workflow that calls php stan:
```
      - name: Run php stan static analysis
        run: composer run-script phpstan
```

And the composer script is as follows:
```
		"phpstan": [
			"./vendor/bin/phpstan analyse"
		],
```

If I run the same composer script locally, everything passes, but in the workflow it fails.
So just on a hunch I added -V to the command to see what version is being used, and locally I get:
```
gmaddock@Wrecked:/var/www/dev-events$ composer run-script phpstan
> ./vendor/bin/phpstan analyse -V
PHPStan - PHP Static Analysis Tool 1.9.4
```

But in the workflow I'm getting a different version:
```
Run composer run-script phpstan
> ./vendor/bin/phpstan analyse -V
PHPStan - PHP Static Analysis ToolPHPStan - PHP Static Analysis Tool 1.10.5
```

Shouldn't it be the same version if it's in the vendor package?  What am I missing?

**Comment by geoff-maddock** [comment]
For reference, he's my whole workflow up to the part where phpstan fails:
```
name: PHP Composer

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8.0
        env:
          ## Accessing to Github secrets, where you can store your configuration
          MYSQL_ALLOW_EMPTY_PASSWORD: false
          MYSQL_ROOT_PASSWORD: db-password
          MYSQL_DATABASE: event-repo-db-name
        ## map the "external" 33306 port with the "internal" 3306
        ports:
          - 33306:3306
        # Set health checks to wait until mysql database has started (it takes some seconds to start)
        options: >-
          --health-cmd="mysqladmin ping"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.1
          extensions: intl #optional
          ini-values: "post_max_size=256M" #optional

      - name: Check PHP Version
        run: php

      - name: Copy .env
        run: php -r "file_exists('.env') || copy('.env.example', '.env');"

      - name: Validate composer.json and composer.lock
        run: composer validate

      - name: Install dependencies
        run: composer install --quiet --no-ansi --no-interaction --no-scripts --no-suggest --no-progress --prefer-dist

      - name: Install NPM Dependencies
        run: npm install

      - name: Clear Config
        run: php artisan config:clear

      - name: Generate Key
        run: php artisan key:generate

      - name: Create asset storage path
        run: mkdir -p ${{ github.workspace }}/public/storage/photos

      - name: Create symlink
        run: php artisan storage:link

      - name: Echo the php stan config:clear
        run: more phpstan.neon.dist

      - name: Run php stan static analysis
        run: composer run-script phpstan
        ```
