### DISCUSSION TITLE
can you create a new release for "feat: support Laravel 11 casts method"?

### DISCUSSION THREAD

**Discussion by adamgyongyosi** [larastan/larastan#1941] [General]
hello

can you crate a new version for "feat: support Laravel 11 casts method"?

**Comment by szepeviktor** [comment]
Yes. It takes only a minute.
We have to wait for @canvural

**Comment by szepeviktor** [comment]
@adamgyongyosi Until that: `"larastan/larastan": "dev-2.x",`

**Reply by adamgyongyosi** [reply]
composer
```
 - Downloading larastan/larastan (2.x-dev 66db15f)
 - Installing larastan/larastan (2.x-dev 66db15f): Extracting archive
```

![image](https://github.com/larastan/larastan/assets/5511526/09d5a267-c3bf-4389-afec-1962fafb1377)


backend/phpstan.neon
```
includes:
    - ./vendor/larastan/larastan/extension.neon

parameters:

    paths:
        - app
        - config
        - database
        - routes

    # The level 9 is the highest level
    level: 5

    parallel:
        maximumNumberOfProcesses: 4

    noUnnecessaryCollectionCall: false
    checkMissingIterableValueType: false
    treatPhpDocTypesAsCertain: false

```

model
![image](https://github.com/larastan/larastan/assets/5511526/8b3a4cc2-34c8-44f9-b9a5-a0b3303fd447)
