### DISCUSSION TITLE
Call to an undefined static method on a macro

### DISCUSSION THREAD

**Discussion by ahoiroman** [larastan/larastan#2084] [Q&A]
Hey there,

I added a macro to my AppServiceProvider like this:

```
Cache::macro('staleWhileRevalidate', function ($key, $ttl, $callback) {
    if (Cache::has($key)) {
        App::terminating(fn() => Cache::put($key, $callback(), $ttl));
    }

    return Cache::remember($key, $ttl, $callback);
});
```

Unfortunately, Larastan does not get it:

>   117    Call to an undefined static method                         
         Illuminate\Support\Facades\Cache::staleWhileRevalidate().  

How can I tell Larastan, what this is?

**Comment by calebdw** [comment]
Are you actually using Larastan? What does your `phpstan.neon(.dist)` look like?

I ask because I've seen cases where someone had Larastan installed but never configured PHPStan to use it

**Reply by ahoiroman** [reply]
I think so ;-)

```
includes:
    - vendor/larastan/larastan/extension.neon

parameters:

    paths:
        - app/

    # Level 9 is the highest level
    level: 5

#    ignoreErrors:
#        - '#PHPDoc tag @var#'
#
#    excludePaths:
#        - ./*/*/FileToBeExcluded.php
#
#    checkMissingIterableValueType: false
```
